"""
MedinexAI — Symptom Synonym Map
Maps colloquial / informal / misspelled phrases to the canonical symptom tokens
used in the training dataset (underscore-separated format).

The keys are lowercase phrases a user might type.
The values are the exact symptom names from dataset.csv.
"""

SYNONYM_MAP: dict[str, str] = {
    # ── Head & Neurological ──────────────────────────────────────────────
    "head pain": "headache",
    "head ache": "headache",
    "head hurts": "headache",
    "my head hurts": "headache",
    "splitting headache": "headache",
    "migraine headache": "headache",
    "throbbing head": "headache",
    "pounding headache": "headache",
    "head killing me": "headache",
    "head is killing me": "headache",
    "head is killing": "headache",
    "my head is killing": "headache",
    "terrible headache": "headache",
    "severe headache": "headache",
    "bad headache": "headache",
    "headace": "headache",
    "dizzy": "dizziness",
    "feeling dizzy": "dizziness",
    "lightheaded": "dizziness",
    "light headed": "dizziness",
    "vertigo": "dizziness",
    "room spinning": "spinning_movements",
    "world spinning": "spinning_movements",
    "spinning sensation": "spinning_movements",
    "spinning": "spinning_movements",
    "loss of balance": "loss_of_balance",
    "off balance": "loss_of_balance",
    "balance problems": "loss_of_balance",
    "unsteady": "unsteadiness",
    "unsteady gait": "unsteadiness",
    "wobbling": "unsteadiness",
    "wobbly": "unsteadiness",
    "slurred speech": "slurred_speech",
    "speech difficulty": "slurred_speech",
    "trouble speaking": "slurred_speech",
    "cant speak properly": "slurred_speech",
    "can't speak properly": "slurred_speech",
    "one side weakness": "weakness_of_one_body_side",
    "one sided weakness": "weakness_of_one_body_side",
    "weak on one side": "weakness_of_one_body_side",
    "half body weak": "weakness_of_one_body_side",
    "paralysis one side": "weakness_of_one_body_side",
    "loss of smell": "loss_of_smell",
    "can't smell": "loss_of_smell",
    "cant smell": "loss_of_smell",
    "no smell": "loss_of_smell",
    "anosmia": "loss_of_smell",
    "altered consciousness": "altered_sensorium",
    "confused": "altered_sensorium",
    "confusion": "altered_sensorium",
    "disoriented": "altered_sensorium",
    "mental confusion": "altered_sensorium",
    "unconscious": "coma",
    "not waking up": "coma",
    "in a coma": "coma",
    "unresponsive": "coma",
    "lack of focus": "lack_of_concentration",
    "can't concentrate": "lack_of_concentration",
    "cant concentrate": "lack_of_concentration",
    "poor concentration": "lack_of_concentration",
    "difficulty concentrating": "lack_of_concentration",
    "brain fog": "lack_of_concentration",
    "vision problems": "visual_disturbances",
    "visual disturbance": "visual_disturbances",
    "blurry vision": "blurred_and_distorted_vision",
    "blurred vision": "blurred_and_distorted_vision",
    "blurry eyesight": "blurred_and_distorted_vision",
    "can't see clearly": "blurred_and_distorted_vision",
    "distorted vision": "blurred_and_distorted_vision",
    "fuzzy vision": "blurred_and_distorted_vision",

    # ── Fever & Temperature ──────────────────────────────────────────────
    "high temperature": "high_fever",
    "high fever": "high_fever",
    "burning up": "high_fever",
    "very hot": "high_fever",
    "fever": "high_fever",
    "temperature": "high_fever",
    "feverish": "high_fever",
    "low grade fever": "mild_fever",
    "mild temperature": "mild_fever",
    "slight fever": "mild_fever",
    "low fever": "mild_fever",
    "mild fever": "mild_fever",
    "subfebril": "mild_fever",

    # ── Gastrointestinal ─────────────────────────────────────────────────
    "throwing up": "vomiting",
    "vomit": "vomiting",
    "puking": "vomiting",
    "puke": "vomiting",
    "need to puke": "vomiting",
    "want to puke": "vomiting",
    "going to puke": "vomiting",
    "barfing": "vomiting",
    "being sick": "vomiting",
    "keep vomiting": "vomiting",
    "keep throwing up": "vomiting",
    "feeling nauseous": "nausea",
    "nauseous": "nausea",
    "queasy": "nausea",
    "nausia": "nausea",
    "feel like vomiting": "nausea",
    "sick to my stomach": "nausea",
    "tummy ache": "stomach_pain",
    "stomach ache": "stomach_pain",
    "stomach hurts": "stomach_pain",
    "tummy pain": "stomach_pain",
    "stomach cramps": "stomach_pain",
    "epigastric pain": "stomach_pain",
    "belly ache": "belly_pain",
    "belly hurts": "belly_pain",
    "belly cramps": "belly_pain",
    "lower belly pain": "belly_pain",
    "abdominal cramps": "abdominal_pain",
    "abdomen pain": "abdominal_pain",
    "abdominal ache": "abdominal_pain",
    "tummy cramps": "abdominal_pain",
    "heartburn": "acidity",
    "acid reflux": "acidity",
    "sour stomach": "acidity",
    "acid stomach": "acidity",
    "bloating": "indigestion",
    "upset stomach": "indigestion",
    "indigestion": "indigestion",
    "dyspepsia": "indigestion",
    "diarrhea": "diarrhoea",
    "diarhea": "diarrhoea",
    "loose stools": "diarrhoea",
    "loose motions": "diarrhoea",
    "watery stool": "diarrhoea",
    "runny stool": "diarrhoea",
    "frequent stools": "diarrhoea",
    "constipated": "constipation",
    "can't poop": "constipation",
    "cant poop": "constipation",
    "hard stool": "constipation",
    "difficulty passing stool": "constipation",
    "not hungry": "loss_of_appetite",
    "no appetite": "loss_of_appetite",
    "don't want to eat": "loss_of_appetite",
    "lost appetite": "loss_of_appetite",
    "appetite loss": "loss_of_appetite",
    "not eating": "loss_of_appetite",
    "always hungry": "excessive_hunger",
    "excessive appetite": "excessive_hunger",
    "eating too much": "excessive_hunger",
    "increased hunger": "excessive_hunger",
    "ravenous": "excessive_hunger",
    "mouth ulcers": "ulcers_on_tongue",
    "tongue ulcers": "ulcers_on_tongue",
    "sores on tongue": "ulcers_on_tongue",
    "oral ulcers": "ulcers_on_tongue",
    "gas": "passage_of_gases",
    "passing gas": "passage_of_gases",
    "flatulence": "passage_of_gases",
    "bloated stomach": "swelling_of_stomach",
    "stomach bloating": "swelling_of_stomach",
    "swollen stomach": "swelling_of_stomach",
    "distended abdomen": "distention_of_abdomen",
    "bloated abdomen": "distention_of_abdomen",
    "blood in stool": "bloody_stool",
    "bloody poop": "bloody_stool",
    "rectal bleeding": "bloody_stool",
    "pain during bowel movement": "pain_during_bowel_movements",
    "painful bowel movement": "pain_during_bowel_movements",
    "hurts when pooping": "pain_during_bowel_movements",
    "anal pain": "pain_in_anal_region",
    "butt pain": "pain_in_anal_region",
    "rectal pain": "pain_in_anal_region",
    "anal irritation": "irritation_in_anus",
    "itchy anus": "irritation_in_anus",
    "rectal itching": "irritation_in_anus",
    "stomach bleeding": "stomach_bleeding",
    "internal bleeding": "stomach_bleeding",
    "gi bleeding": "stomach_bleeding",

    # ── Respiratory & Throat ─────────────────────────────────────────────
    "coughing": "cough",
    "dry cough": "cough",
    "wet cough": "cough",
    "persistent cough": "cough",
    "sneezing": "continuous_sneezing",
    "constant sneezing": "continuous_sneezing",
    "non stop sneezing": "continuous_sneezing",
    "keep sneezing": "continuous_sneezing",
    "runny nose": "runny_nose",
    "running nose": "runny_nose",
    "nasal discharge": "runny_nose",
    "nose running": "runny_nose",
    "stuffy nose": "congestion",
    "blocked nose": "congestion",
    "nasal congestion": "congestion",
    "nose blocked": "congestion",
    "stuffed up": "congestion",
    "sinus": "sinus_pressure",
    "sinus pain": "sinus_pressure",
    "sinus headache": "sinus_pressure",
    "sinusitis": "sinus_pressure",
    "short of breath": "breathlessness",
    "shortness of breath": "breathlessness",
    "can't breathe": "breathlessness",
    "cant breathe": "breathlessness",
    "difficulty breathing": "breathlessness",
    "dyspnea": "breathlessness",
    "breathless": "breathlessness",
    "hard to breathe": "breathlessness",
    "wheezing": "breathlessness",
    "sore throat": "throat_irritation",
    "throat pain": "throat_irritation",
    "scratchy throat": "throat_irritation",
    "throat hurts": "throat_irritation",
    "itchy throat": "throat_irritation",
    "throat irritation": "throat_irritation",
    "mucus": "phlegm",
    "phlegm": "phlegm",
    "sputum": "phlegm",
    "mucus cough": "phlegm",
    "coughing up blood": "blood_in_sputum",
    "blood in mucus": "blood_in_sputum",
    "bloody sputum": "blood_in_sputum",
    "hemoptysis": "blood_in_sputum",
    "rusty colored sputum": "rusty_sputum",
    "brown sputum": "rusty_sputum",
    "mucoid sputum": "mucoid_sputum",
    "thick mucus": "mucoid_sputum",

    # ── Chest & Heart ────────────────────────────────────────────────────
    "chest pain": "chest_pain",
    "chest tightness": "chest_pain",
    "chest hurts": "chest_pain",
    "pain in chest": "chest_pain",
    "heart racing": "fast_heart_rate",
    "rapid heartbeat": "fast_heart_rate",
    "fast heartbeat": "fast_heart_rate",
    "tachycardia": "fast_heart_rate",
    "heart pounding": "fast_heart_rate",
    "heart palpitations": "palpitations",
    "heart fluttering": "palpitations",
    "irregular heartbeat": "palpitations",
    "skipped heartbeat": "palpitations",

    # ── Skin ─────────────────────────────────────────────────────────────
    "itchy": "itching",
    "itchy skin": "itching",
    "itchiness": "itching",
    "scratching": "itching",
    "itch": "itching",
    "body itch": "itching",
    "rash": "skin_rash",
    "skin rash": "skin_rash",
    "rashes": "skin_rash",
    "hives": "skin_rash",
    "skin eruption": "skin_rash",
    "yellow skin": "yellowish_skin",
    "yellowish skin": "yellowish_skin",
    "jaundiced skin": "yellowish_skin",
    "skin yellowing": "yellowish_skin",
    "skin peeling": "skin_peeling",
    "peeling skin": "skin_peeling",
    "flaky skin": "skin_peeling",
    "discolored patches": "dischromic_patches",
    "skin discoloration": "dischromic_patches",
    "skin patches": "dischromic_patches",
    "dark patches": "dischromic_patches",
    "skin bumps": "nodal_skin_eruptions",
    "nodules on skin": "nodal_skin_eruptions",
    "lumps on skin": "nodal_skin_eruptions",
    "pimples": "pus_filled_pimples",
    "pus pimples": "pus_filled_pimples",
    "zits": "pus_filled_pimples",
    "acne": "pus_filled_pimples",
    "blackheads": "blackheads",
    "black heads": "blackheads",
    "scarring": "scurring",
    "scars": "scurring",
    "acne scars": "scurring",
    "silver scales": "silver_like_dusting",
    "silvery scales": "silver_like_dusting",
    "silver dust on skin": "silver_like_dusting",
    "blisters": "blister",
    "skin blister": "blister",
    "water blister": "blister",
    "sore around nose": "red_sore_around_nose",
    "red nose sore": "red_sore_around_nose",
    "nose sore": "red_sore_around_nose",
    "yellow crust": "yellow_crust_ooze",
    "crusty ooze": "yellow_crust_ooze",
    "oozing sores": "yellow_crust_ooze",
    "red spots": "red_spots_over_body",
    "red spots on body": "red_spots_over_body",
    "red dots": "red_spots_over_body",
    "spotty body": "red_spots_over_body",
    "bruises": "bruising",
    "bruise easily": "bruising",
    "easy bruising": "bruising",

    # ── Pain & Musculoskeletal ───────────────────────────────────────────
    "back pain": "back_pain",
    "backache": "back_pain",
    "back ache": "back_pain",
    "lower back pain": "back_pain",
    "upper back pain": "back_pain",
    "back hurts": "back_pain",
    "neck pain": "neck_pain",
    "neck ache": "neck_pain",
    "neck hurts": "neck_pain",
    "stiff neck": "stiff_neck",
    "neck stiffness": "stiff_neck",
    "joint pain": "joint_pain",
    "joint ache": "joint_pain",
    "joints hurt": "joint_pain",
    "achy joints": "joint_pain",
    "arthralgia": "joint_pain",
    "knee pain": "knee_pain",
    "knee hurts": "knee_pain",
    "knees hurt": "knee_pain",
    "knees hurting": "knee_pain",
    "knee ache": "knee_pain",
    "my knee hurts": "knee_pain",
    "my knees hurt": "knee_pain",
    "bad knee": "knee_pain",
    "hip pain": "hip_joint_pain",
    "hip hurts": "hip_joint_pain",
    "hip ache": "hip_joint_pain",
    "hip joint pain": "hip_joint_pain",
    "joint swelling": "swelling_joints",
    "swollen joints": "swelling_joints",
    "joints swollen": "swelling_joints",
    "stiffness": "movement_stiffness",
    "movement stiffness": "movement_stiffness",
    "stiff joints": "movement_stiffness",
    "difficulty moving": "movement_stiffness",
    "hard to walk": "painful_walking",
    "painful walking": "painful_walking",
    "difficulty walking": "painful_walking",
    "limping": "painful_walking",
    "hurts to walk": "painful_walking",
    "muscle pain": "muscle_pain",
    "muscle ache": "muscle_pain",
    "body ache": "muscle_pain",
    "body aches": "muscle_pain",
    "body pain": "muscle_pain",
    "body pains": "muscle_pain",
    "aching body": "muscle_pain",
    "whole body hurts": "muscle_pain",
    "myalgia": "muscle_pain",
    "sore muscles": "muscle_pain",
    "weak muscles": "muscle_weakness",
    "muscle weakness": "muscle_weakness",
    "muscles feel weak": "muscle_weakness",
    "muscle loss": "muscle_wasting",
    "muscle wasting": "muscle_wasting",
    "muscle atrophy": "muscle_wasting",
    "cramps": "cramps",
    "cramping": "cramps",
    "muscle cramp": "cramps",
    "leg cramps": "cramps",
    "pain behind eyes": "pain_behind_the_eyes",
    "eye pain": "pain_behind_the_eyes",
    "eyes hurt": "pain_behind_the_eyes",
    "behind eye pain": "pain_behind_the_eyes",
    "weak limbs": "weakness_in_limbs",
    "limb weakness": "weakness_in_limbs",
    "arms and legs weak": "weakness_in_limbs",
    "weak arms and legs": "weakness_in_limbs",

    # ── Eyes ─────────────────────────────────────────────────────────────
    "red eyes": "redness_of_eyes",
    "eye redness": "redness_of_eyes",
    "bloodshot eyes": "redness_of_eyes",
    "eyes are red": "redness_of_eyes",
    "watery eyes": "watering_from_eyes",
    "eyes watering": "watering_from_eyes",
    "tearing eyes": "watering_from_eyes",
    "teary eyes": "watering_from_eyes",
    "yellow eyes": "yellowing_of_eyes",
    "eyes turning yellow": "yellowing_of_eyes",
    "yellowing eyes": "yellowing_of_eyes",
    "jaundiced eyes": "yellowing_of_eyes",
    "sunken eyes": "sunken_eyes",
    "hollow eyes": "sunken_eyes",
    "dark circles": "sunken_eyes",
    "puffy eyes": "puffy_face_and_eyes",
    "swollen face": "puffy_face_and_eyes",
    "puffy face": "puffy_face_and_eyes",
    "face swelling": "puffy_face_and_eyes",

    # ── Urinary ──────────────────────────────────────────────────────────
    "painful urination": "burning_micturition",
    "burning urination": "burning_micturition",
    "burns when i pee": "burning_micturition",
    "burning pee": "burning_micturition",
    "dysuria": "burning_micturition",
    "burning when peeing": "burning_micturition",
    "spotting urine": "spotting_urination",
    "blood in urine": "spotting_urination",
    "dark urine": "dark_urine",
    "dark pee": "dark_urine",
    "brown urine": "dark_urine",
    "cola colored urine": "dark_urine",
    "yellow urine": "yellow_urine",
    "bright yellow pee": "yellow_urine",
    "smelly urine": "foul_smell_of_urine",
    "foul smelling urine": "foul_smell_of_urine",
    "stinky pee": "foul_smell_of_urine",
    "bad smelling urine": "foul_smell_of_urine",
    "urine smell": "foul_smell_of_urine",
    "frequent urination": "continuous_feel_of_urine",
    "always need to pee": "continuous_feel_of_urine",
    "constant urge to urinate": "continuous_feel_of_urine",
    "urge to pee": "continuous_feel_of_urine",
    "peeing a lot": "polyuria",
    "excessive urination": "polyuria",
    "lots of urine": "polyuria",
    "bladder pain": "bladder_discomfort",
    "bladder discomfort": "bladder_discomfort",
    "bladder pressure": "bladder_discomfort",

    # ── Energy & Mood ────────────────────────────────────────────────────
    "tired": "fatigue",
    "exhausted": "fatigue",
    "fatigue": "fatigue",
    "tiredness": "fatigue",
    "feeling tired": "fatigue",
    "no energy": "fatigue",
    "worn out": "fatigue",
    "sluggish": "lethargy",
    "lethargic": "lethargy",
    "lazy feeling": "lethargy",
    "no motivation": "lethargy",
    "lethargy": "lethargy",
    "can't sleep": "restlessness",
    "cant sleep": "restlessness",
    "insomnia": "restlessness",
    "restless": "restlessness",
    "sleepless": "restlessness",
    "tossing and turning": "restlessness",
    "anxious": "anxiety",
    "anxiety": "anxiety",
    "nervous": "anxiety",
    "worried": "anxiety",
    "panic": "anxiety",
    "feeling anxious": "anxiety",
    "depressed": "depression",
    "depression": "depression",
    "sad": "depression",
    "feeling down": "depression",
    "hopeless": "depression",
    "feeling hopeless": "depression",
    "mood swings": "mood_swings",
    "emotional": "mood_swings",
    "irritable": "irritability",
    "easily annoyed": "irritability",
    "short tempered": "irritability",
    "cranky": "irritability",
    "grumpy": "irritability",
    "feeling weak": "malaise",
    "generally unwell": "malaise",
    "malaise": "malaise",
    "feeling unwell": "malaise",
    "not feeling well": "malaise",

    # ── Weight & Metabolism ──────────────────────────────────────────────
    "gaining weight": "weight_gain",
    "putting on weight": "weight_gain",
    "weight gain": "weight_gain",
    "getting fat": "weight_gain",
    "losing weight": "weight_loss",
    "weight loss": "weight_loss",
    "unintentional weight loss": "weight_loss",
    "dropping weight": "weight_loss",
    "obese": "obesity",
    "overweight": "obesity",
    "very fat": "obesity",
    "obesity": "obesity",
    "blood sugar issues": "irregular_sugar_level",
    "irregular sugar": "irregular_sugar_level",
    "blood sugar fluctuations": "irregular_sugar_level",
    "sugar levels": "irregular_sugar_level",
    "high blood sugar": "irregular_sugar_level",
    "low blood sugar": "irregular_sugar_level",
    "increased appetite": "increased_appetite",
    "eating more": "increased_appetite",
    "hungry all the time": "increased_appetite",

    # ── General / Systemic ───────────────────────────────────────────────
    "shivering": "shivering",
    "shaking": "shivering",
    "trembling": "shivering",
    "chills": "chills",
    "feeling cold": "chills",
    "cold chills": "chills",
    "goosebumps": "chills",
    "sweating": "sweating",
    "sweating a lot": "sweating",
    "night sweats": "sweating",
    "perspiration": "sweating",
    "excessive sweating": "sweating",
    "dehydrated": "dehydration",
    "dehydration": "dehydration",
    "dry mouth": "dehydration",
    "very thirsty": "dehydration",
    "cold hands": "cold_hands_and_feets",
    "cold feet": "cold_hands_and_feets",
    "cold hands and feet": "cold_hands_and_feets",
    "cold extremities": "cold_hands_and_feets",
    "swollen legs": "swollen_legs",
    "leg swelling": "swollen_legs",
    "legs swollen": "swollen_legs",
    "edema legs": "swollen_legs",
    "swollen blood vessels": "swollen_blood_vessels",
    "varicose": "swollen_blood_vessels",
    "veins bulging": "swollen_blood_vessels",
    "prominent veins": "prominent_veins_on_calf",
    "veins on calf": "prominent_veins_on_calf",
    "calf veins": "prominent_veins_on_calf",
    "swollen lymph nodes": "swelled_lymph_nodes",
    "lymph nodes swollen": "swelled_lymph_nodes",
    "enlarged lymph nodes": "swelled_lymph_nodes",
    "glands swollen": "swelled_lymph_nodes",
    "swollen glands": "swelled_lymph_nodes",
    "swollen extremities": "swollen_extremeties",
    "puffy hands and feet": "swollen_extremeties",
    "swollen hands": "swollen_extremeties",
    "enlarged thyroid": "enlarged_thyroid",
    "thyroid swelling": "enlarged_thyroid",
    "goiter": "enlarged_thyroid",
    "goitre": "enlarged_thyroid",
    "brittle nails": "brittle_nails",
    "nails breaking": "brittle_nails",
    "weak nails": "brittle_nails",
    "nail dents": "small_dents_in_nails",
    "dents in nails": "small_dents_in_nails",
    "pitted nails": "small_dents_in_nails",
    "nail inflammation": "inflammatory_nails",
    "inflamed nails": "inflammatory_nails",
    "swollen nails": "inflammatory_nails",
    "dry lips": "drying_and_tingling_lips",
    "tingling lips": "drying_and_tingling_lips",
    "lips tingling": "drying_and_tingling_lips",
    "numb lips": "drying_and_tingling_lips",

    # ── Liver-specific ───────────────────────────────────────────────────
    "liver failure": "acute_liver_failure",
    "liver damage": "acute_liver_failure",
    "liver failing": "acute_liver_failure",
    "fluid retention": "fluid_overload",
    "fluid overload": "fluid_overload",
    "edema": "fluid_overload",
    "swelling": "fluid_overload",
    "drinking history": "history_of_alcohol_consumption",
    "alcohol history": "history_of_alcohol_consumption",
    "heavy drinking": "history_of_alcohol_consumption",
    "alcoholic": "history_of_alcohol_consumption",
    "drinks alcohol": "history_of_alcohol_consumption",

    # ── Risk factors / History ───────────────────────────────────────────
    "family history": "family_history",
    "runs in family": "family_history",
    "genetic history": "family_history",
    "hereditary": "family_history",
    "blood transfusion": "receiving_blood_transfusion",
    "received blood": "receiving_blood_transfusion",
    "transfusion": "receiving_blood_transfusion",
    "unsterile injection": "receiving_unsterile_injections",
    "dirty needle": "receiving_unsterile_injections",
    "shared needle": "receiving_unsterile_injections",
    "unclean injection": "receiving_unsterile_injections",
    "unprotected contact": "extra_marital_contacts",
    "extramarital": "extra_marital_contacts",
    "risky sexual contact": "extra_marital_contacts",
    "unsafe sex": "extra_marital_contacts",
    "multiple partners": "extra_marital_contacts",
    "abnormal periods": "abnormal_menstruation",
    "irregular periods": "abnormal_menstruation",
    "period problems": "abnormal_menstruation",
    "menstrual irregularity": "abnormal_menstruation",
    "heavy periods": "abnormal_menstruation",
    "missed periods": "abnormal_menstruation",
    "patches in throat": "patches_in_throat",
    "white patches throat": "patches_in_throat",
    "throat patches": "patches_in_throat",
    "internal itching": "internal_itching",
    "itching inside": "internal_itching",
    "itch inside body": "internal_itching",
    "toxic look": "toxic_look_(typhos)",
    "typhos": "toxic_look_(typhos)",
    "toxemia": "toxic_look_(typhos)",

    # ── Common typos ─────────────────────────────────────────────────────
    "headach": "headache",
    "hedache": "headache",
    "haedache": "headache",
    "nausia": "nausea",
    "nausae": "nausea",
    "voiting": "vomiting",
    "vommiting": "vomiting",
    "vomitting": "vomiting",
    "diarhea": "diarrhoea",
    "diarrea": "diarrhoea",
    "diahrea": "diarrhoea",
    "diahrrea": "diarrhoea",
    "brethlessness": "breathlessness",
    "breathlesness": "breathlessness",
    "coughing": "cough",
    "cofing": "cough",
    "fatige": "fatigue",
    "fatuge": "fatigue",
    "fatigu": "fatigue",
    "constaption": "constipation",
    "constipaton": "constipation",
    "consitpation": "constipation",
    "itchng": "itching",
    "itchiing": "itching",
    "dizzyness": "dizziness",
    "dizzines": "dizziness",
    "diziness": "dizziness",
    "anxeity": "anxiety",
    "anxity": "anxiety",
    "depresion": "depression",
    "dipression": "depression",
    "muscl pain": "muscle_pain",
    "musle pain": "muscle_pain",
    "stomache pain": "stomach_pain",
    "stomack pain": "stomach_pain",
    "chest pian": "chest_pain",
    "chets pain": "chest_pain",
    "palpatations": "palpitations",
    "palpitaions": "palpitations",
}
